# Generated by Django 5.0.1 on 2024-01-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='contacts',
        ),
        migrations.AddField(
            model_name='provider',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.contact', verbose_name='контакты'),
        ),
    ]
