# Generated by Django 5.0.1 on 2024-01-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_provider_contacts_provider_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='products',
        ),
        migrations.AddField(
            model_name='contact',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='shop.provider', verbose_name='поставщик'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.provider', verbose_name='поставщик'),
        ),
    ]
