# Generated by Django 5.0.1 on 2024-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_contact_title_remove_provider_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='почта'),
        ),
    ]
