# Generated by Django 5.0.1 on 2024-01-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_provider_linked_url_remove_contact_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.contact', verbose_name='контакт'),
        ),
        migrations.AddField(
            model_name='provider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выхода продукта на рынок'),
        ),
    ]
