# Generated by Django 5.0.1 on 2024-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_contact_provider_remove_product_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='product',
        ),
        migrations.AddField(
            model_name='provider',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='shop.contact', verbose_name='контакт'),
        ),
        migrations.AddField(
            model_name='provider',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product', verbose_name='продукт'),
        ),
    ]
