# Generated by Django 5.0.1 on 2024-01-08 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_provider_contact_remove_provider_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.provider', verbose_name='поставщик'),
        ),
    ]
